"""shelves, reservations, notifications, favorites, user admin fields

Revision ID: fbf3dd278a42
Revises: 0002_core_schema
Create Date: 2026-09-09 19:41:56.343463
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_engagement"
down_revision: str | None = "0002_core_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shelves',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('due_reminder', 'overdue', 'reservation_ready', 'reservation_expired', 'fine_issued', 'new_book', 'recommendation', 'announcement', name='notification_type', native_enum=False, length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notif_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'book_id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'fulfilled', 'cancelled', 'expired', name='reservation_status', native_enum=False, length=30), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_loan_id', sa.Uuid(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fulfilled_loan_id'], ['loans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_book_id'), ['book_id'], unique=False)
        batch_op.create_index('ix_reservations_book_status', ['book_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reservations_user_status', ['user_id', 'status'], unique=False)

    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelf_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_book_copies_shelf_id'), ['shelf_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_book_copies_shelf_id', 'shelves', ['shelf_id'], ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrow_limit_override', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('staff_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('staff_notes')
        batch_op.drop_column('borrow_limit_override')

    with op.batch_alter_table('book_copies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_book_copies_shelf_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_book_copies_shelf_id'))
        batch_op.drop_column('shelf_id')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index('ix_reservations_user_status')
        batch_op.drop_index(batch_op.f('ix_reservations_user_id'))
        batch_op.drop_index('ix_reservations_book_status')
        batch_op.drop_index(batch_op.f('ix_reservations_book_id'))

    op.drop_table('reservations')
    op.drop_table('favorites')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notif_user_read')

    op.drop_table('notifications')
    op.drop_table('shelves')
    # ### end Alembic commands ###
